"""
Day 4 — executes a policy-approved RecoveryCase against Razorpay Test Mode.

Only ever called for cases whose policy verdict was EXECUTE
(case.status == "pending_execution", set by app/policy_runner.py). For each
call:

  1. Create one Action row. idempotency_key is auto-generated by the Action
     model itself (see models.py's `default=lambda: uuid.uuid4().hex`) —
     generated once, at object-creation time, in Python, before any network
     call happens. That means a retried execution call against the same
     Action reuses the exact same key rather than minting a new one, which
     is what actually prevents a double-send on a retried request — not a
     comment saying it should.
  2. Check the "razorpay" circuit breaker (reused from
     app/agents/circuit_breaker.py — tier-name-agnostic, so a third caller
     from outside app/agents/ costs nothing to add).
  3. Check a dedicated rate-limit bucket (key="razorpay_execute") — separate
     from /cases/{id}/analyze's bucket, see app/rate_limit.py's Day 4 update.
  4. Call Razorpay's Payment Links API once via app/razorpay_client.py.
  5. Write the outcome back onto the same Action row, update case.status,
     and write an audit_log entry at every stage (started / failed /
     succeeded) — the PRD's "full audit trail" requirement, and PROGRESS.md's
     "every decision + API call in audit_log" Day 4 item.

Every exit path (circuit open, rate limited, Razorpay error, success)
commits its own audit_log row and case.status update before returning or
raising, so a case is never left in "pending_execution" limbo after this
function has been called once.
"""
from sqlalchemy.orm import Session

from app.agents import circuit_breaker
from app.models import Action, AgentDecision, AuditLog, RecoveryCase
from app.rate_limit import RateLimitExceeded, check_and_record
from app.razorpay_client import RazorpayClient, RazorpayError

RAZORPAY_RATE_LIMIT_PER_MINUTE = 15
RAZORPAY_RATE_LIMIT_KEY = "razorpay_execute"

# Razorpay itself handles notifying the customer for these actions (email +
# SMS via the `notify` flag on the Payment Link); retry_now/retry_later are
# treated as quieter, system-initiated nudges and don't ask Razorpay to notify.
_NOTIFY_ACTIONS = {"send_payment_link"}


class CaseNotPendingExecutionError(Exception):
    """Raised when execution is attempted on a case whose policy verdict
    wasn't EXECUTE (case.status != 'pending_execution') — nothing to do."""


class CircuitOpenError(Exception):
    """Raised when the Razorpay circuit breaker is currently open. Caller
    should treat this the same as any other execution failure."""


def _latest_strategy_action(db: Session, case_id: int) -> str:
    decision = (
        db.query(AgentDecision)
        .filter(AgentDecision.recovery_case_id == case_id, AgentDecision.agent_name == "recovery_strategy_agent")
        .order_by(AgentDecision.created_at.desc(), AgentDecision.id.desc())
        .first()
    )
    return decision.output["action"]


def _fail(db: Session, case: RecoveryCase, action: Action, reason: str, event_type: str = "execution_failed") -> None:
    action.status = "failed"
    case.status = "execution_failed"
    db.add(
        AuditLog(
            recovery_case_id=case.id,
            event_type=event_type,
            payload={"reason": reason, "idempotency_key": action.idempotency_key},
        )
    )
    db.commit()


def execute_case(db: Session, case: RecoveryCase, razorpay: RazorpayClient | None = None) -> dict:
    if case.status != "pending_execution":
        raise CaseNotPendingExecutionError(
            f"Case {case.id} has status '{case.status}', not 'pending_execution' — "
            "policy evaluation must return EXECUTE before this can run."
        )

    razorpay = razorpay if razorpay is not None else RazorpayClient()
    action_type = _latest_strategy_action(db, case.id)

    payment = case.payment
    order = payment.order
    customer = order.customer

    action = Action(recovery_case_id=case.id, action_type=action_type, status="pending")
    db.add(action)
    db.flush()  # assigns action.id + idempotency_key default before we call out or audit-log it

    db.add(
        AuditLog(
            recovery_case_id=case.id,
            event_type="execution_started",
            payload={"action_type": action_type, "idempotency_key": action.idempotency_key},
        )
    )
    db.commit()

    if circuit_breaker.is_open("razorpay"):
        _fail(db, case, action, "razorpay circuit open, call skipped")
        raise CircuitOpenError(f"Razorpay circuit open, case {case.id} not attempted")

    try:
        check_and_record(RAZORPAY_RATE_LIMIT_PER_MINUTE, key=RAZORPAY_RATE_LIMIT_KEY)
    except RateLimitExceeded:
        _fail(db, case, action, "rate limit exceeded")
        raise

    try:
        result = razorpay.create_payment_link(
            amount_paise=order.amount_paise,
            reference_id=action.idempotency_key,
            customer_name=customer.name,
            customer_email=customer.email,
            customer_phone=customer.phone,
            notify=action_type in _NOTIFY_ACTIONS,
        )
    except RazorpayError as exc:
        circuit_breaker.record_failure("razorpay")
        _fail(db, case, action, str(exc))
        raise

    circuit_breaker.record_success("razorpay")
    action.status = "sent"
    action.razorpay_reference = result["id"]
    case.status = "executed"
    db.add(
        AuditLog(
            recovery_case_id=case.id,
            event_type="execution_succeeded",
            payload={
                "razorpay_payment_link_id": result["id"],
                "short_url": result.get("short_url"),
                "idempotency_key": action.idempotency_key,
            },
        )
    )
    db.commit()

    return {
        "action_type": action_type,
        "action_status": action.status,
        "razorpay_reference": action.razorpay_reference,
        "payment_link": result.get("short_url"),
        "case_status": case.status,
    }